            <div class="row">
                <div class="col-sm-9 col-sm-offset-2 col-md-10 col-md-offset-1 main">
                    <p>
                        Please note that this website is still under heavy development!<br />
                        <br />
                        The following is still planned:.<br />
                        <pre>
                            1> Submission moderation queues for the end-user\ s security.
                            2> Map image updating for submissions.
                            3> Map revision rollback for submitters.
                            4> Improved API features for integration with Knights Province (And perhaps KaM Remake).
                            5> Functional map and user flagging for moderation features.
                            6> More in the future. :)
                        </pre>
                    </p><br />
                    <p>
                        Your request :
                        <pre><?=print_r($request, True);?></pre>
                    </p>
                </div>
            </div>