        <div class="container-fluid">
            <!-- Begin Modal HTML -->
            <div id="loginModal" class="modal fade">
                <div class="modal-dialog modal-md">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                            <h4 class="modal-title">Login</h4>
                        </div>
                        <div class="modal-body">
                            <div class="col-md-12 col-sm-12 no-padng">
                                <div class="logreg-model">
                                    <form method="post" action="/login" id="loginFrm" name="loginFrm" class="logreg-frm">
                                        <ul>
                                            <li>Username or Email</li>
                                            <li>
                                                <input type="text" placeholder="Username/Email" id="username" name="username" class="form-control" required>
                                            </li>
                                            <li>Password</li>
                                            <li>
                                                <input type="password" placeholder="Password" id="password" name="password" class="form-control" required>
                                            </li><br />
                                            <li>
                                                <button type="submit" id="logBtn" class="btn btn-default">Submit</button>
                                            </li>
                                        </ul>
                                    </form>
                                    <div class="clearfix"></div>
                                    <form method="post" action="/forgot" id="forgotFrm" name="forgotFrm" class="logreg-frm">
                                        <ul>
                                            <li>
                                                <a class="forgot-link" onclick="toggleForgot();" href="javascript:;">Forgot your password?</a>
                                                <div class="logreg-forgot">
                                                    <ul>
                                                        <li><p>Enter your Email Address here to receive a link to change password.</p></li>
                                                        <li>Email</li>
                                                        <li>
                                                            <input type="email" placeholder="Your email" id="forgetemail" class="form-control" name="forgetemail" required>
                                                        </li>
                                                        <li>
                                                            <button type="submit" class="btn btn-default">Send Mail</button>
                                                        </li>
                                                    </ul>
                                                </div>
                                            </li>
                                        </ul>
                                    </form>
                                </div>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                </div>
            </div>
            <div id="RegisterModal" class="modal fade">
                <div class="modal-dialog modal-md">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                            <h4 class="modal-title">Register</h4>
                        </div>
                        <div class="modal-body">
                            <div class="col-md-12 col-sm-12 no-padng">
                                <div class="logreg-model">
                                    <form method="post" action="/register" id="userRegisterFrm" name="userRegisterFrm" class="logreg-frm">
                                        <ul>
                                            <li>Username</li>
                                            <li>
                                                <input type="text" id="username" name="username" placeholder="Username" class="form-control" required>
                                            </li>
                                            <li>Email</li>
                                            <li>
                                                <input type="email" id="emailAddress" name="emailAddress" placeholder="Email" class="form-control" required>
                                                <input type="email" id="confirmEmailAddress" name="confirmEmailAddress" placeholder="Confirm Email" class="form-control" style="display: none;">
                                            </li>
                                            <li>Password</li>
                                            <li>
                                                <input type="password" id="password" name="password" placeholder="Password" class="form-control" required>
                                            </li>
                                            <li>Confirm Password</li>
                                            <li>
                                                <input type="password" id="confirmPassword" name="confirmPassword" placeholder="Confirm Password" class="form-control" required>
                                            </li>
                                            <br />
                                            <li>
                                                <div id="captchaContainer"></div>
                                            </li>
                                            <br />
                                            <li>
                                                <button type="submit" id="userRegBtn" name="userRegBtn" class="btn btn-default">Signup Now</button>
                                                <button type="button" id="userRegResetBtn" name="userRegResetBtn" class="btn btn-default">Reset</button>
                                            </li>
                                        </ul>
                                    </form>
                                </div>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End Modal HTML -->
            <div class="row">
                <div class="col-sm-9 col-sm-offset-2 col-md-10 col-md-offset-1 main">
                    <p>
                        Please note that this website is still under heavy development!<br />
                        <br />
                        The following is still planned:.<br />
                        <pre>
                            1> Submission moderation queues for the end-user\ s security.
                            2> Map image updating for submissions.
                            3> Map revision rollback for submitters.
                            4> Improved API features for integration with Knights Province (And perhaps KaM Remake).
                            5> Functional map and user flagging for moderation features.
                            6> More in the future. :)
                        </pre>
                    </p><br />
                    <p>
                        Your request :
                        <pre><?=print_r($request, True);?></pre>
                    </p>
                </div>
            </div>
        </div>