        <div class="container-fluid">
            <!-- Begin Modal HTML -->
            <div id="loginModal" class="modal fade">
                <div class="modal-dialog modal-md">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                            <h4 class="modal-title">Login</h4>
                        </div>
                        <div class="modal-body">
                            <div class="col-md-12 col-sm-12 no-padng">
                                <div class="logreg-model">
                                    <form method="post" action="/login" id="loginFrm" name="loginFrm" class="logreg-frm">
                                        <ul>
                                            <li>Username or Email</li>
                                            <li>
                                                <input type="text" placeholder="Username/Email" id="username" name="username" class="form-control" required>
                                            </li>
                                            <li>Password</li>
                                            <li>
                                                <input type="password" placeholder="Password" id="password" name="password" class="form-control" required>
                                            </li><br />
                                            <li>
                                                <button type="submit" id="logBtn" class="btn btn-default">Submit</button>
                                            </li>
                                        </ul>
                                    </form>
                                    <div class="clearfix"></div>
                                    <form method="post" action="/forgot" id="forgotFrm" name="forgotFrm" class="logreg-frm">
                                        <ul>
                                            <li>
                                                <a class="forgot-link" onclick="toggleForgot();" href="javascript:;">Forgot your password?</a>
                                                <div class="logreg-forgot">
                                                    <ul>
                                                        <li><p>Enter your Email Address here to receive a link to change password.</p></li>
                                                        <li>Email</li>
                                                        <li>
                                                            <input type="email" placeholder="Your email" id="forgetemail" class="form-control" name="forgetemail" required>
                                                        </li>
                                                        <li>
                                                            <button type="submit" class="btn btn-default">Send Mail</button>
                                                        </li>
                                                    </ul>
                                                </div>
                                            </li>
                                        </ul>
                                    </form>
                                </div>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                </div>
            </div>
            <div id="RegisterModal" class="modal fade">
                <div class="modal-dialog modal-md">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                            <h4 class="modal-title">Register</h4>
                        </div>
                        <div class="modal-body">
                            <div class="col-md-12 col-sm-12 no-padng">
                                <div class="logreg-model">
                                    <form method="post" action="/register" id="userRegisterFrm" name="userRegisterFrm" class="logreg-frm">
                                        <ul>
                                            <li>Username</li>
                                            <li>
                                                <input type="text" id="username" name="username" placeholder="Username" class="form-control" required>
                                            </li>
                                            <li>Email</li>
                                            <li>
                                                <input type="email" id="emailAddress" name="emailAddress" placeholder="Email" class="form-control" required>
                                                <input type="email" id="confirmEmailAddress" name="confirmEmailAddress" placeholder="Confirm Email" class="form-control" style="display: none;">
                                            </li>
                                            <li>Password</li>
                                            <li>
                                                <input type="password" id="password" name="password" placeholder="Password" class="form-control" required>
                                            </li>
                                            <li>Confirm Password</li>
                                            <li>
                                                <input type="password" id="confirmPassword" name="confirmPassword" placeholder="Confirm Password" class="form-control" required>
                                            </li>
                                            <br />
                                            <li>
                                                <div id="captchaContainer"></div>
                                            </li>
                                            <br />
                                            <li>
                                                <button type="submit" id="userRegBtn" name="userRegBtn" class="btn btn-default">Signup Now</button>
                                                <button type="button" id="userRegResetBtn" name="userRegResetBtn" class="btn btn-default">Reset</button>
                                            </li>
                                        </ul>
                                    </form>
                                </div>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End Modal HTML -->
            <div class="row">
                <div class="col-sm-9 col-sm-offset-2 col-md-10 col-md-offset-1 main">
                    <div class="panel panel-default">
                        <div class="panel-heading">Knights Province Map database</div>
                        <div class="panel-body">
                            <table id="homeTable" class="table table-striped table-bordered table-hover"
                                   data-toggle="table"
                                   data-search="true"
                                   data-sort-name="avg_rating"
                                   data-sort-order="desc"
                                   data-show-toggle="true"
                                   data-show-columns="true"
                                   data-show-export="true"
                                   data-minimum-count-columns="2"
                                   data-url="/api/v1/maps"
                                   data-show-refresh="true"
                                   data-show-pagination-switch="true"
                                   data-pagination="true"
                                   data-page-list="[25, 50, 100, ALL]"
                                   data-page-size="25"
                                   data-show-footer="false"
                                   data-side-pagination="client">
                                <thead>
                                    <tr>
                                        <th class="col-xs-2" data-field="map_type_name" data-sortable="true">Type</th>
                                        <th class="col-xs-2" data-field="map_name" data-formatter="mapNameFormatter" data-sortable="true">Name</th>
                                        <th class="col-xs-2" data-field="user_name" data-formatter="mapAuthorFormatter" data-sortable="true">Author</th>
                                        <th class="col-xs-4" data-field="rev_map_description_short" data-sortable="false">Description</th>
                                        <th class="col-xs-1" data-field="avg_rating" data-sortable="true">Rating</th>
                                        <th class="col-xs-1" data-field="map_downloads" data-sortable="true">Downloads</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>