<div class="row">
    <div class="col-sm-9 col-sm-offset-2 col-md-10 col-md-offset-1 main">
        <div class="panel panel-default">
            <div class="panel-heading">
                <span class="panel-title">Map Queue</span>
            </div>
            <div class="panel-body">
                <table id="mapQueueTable" class="table table-striped table-bordered table-hover" data-toggle="table" data-search="true"
                        data-sort-name="flag_pk" data-sort-order="asc" data-show-toggle="true" data-show-columns="true"
                        data-minimum-count-columns="2" data-url="/api/v1/maps/queue" data-show-refresh="true"
                        data-show-pagination-switch="true" data-pagination="true" data-page-list="[25, 50, 100, ALL]" data-page-size="25"
                        data-show-footer="false" data-side-pagination="client">
                    <thead>
                        <tr>
                            <th class="col-xs-1" data-field="map_type_name" data-sortable="true">Type</th>
                            <th class="col-xs-2" data-field="map_name" data-formatter="mapNameFormatter" data-sortable="true">Name</th>
                            <th class="col-xs-1" data-field="rev_map_version" data-sortable="true">Version</th>
                            <th class="col-xs-6" data-field="rev_map_description_short" data-sortable="false">Description</th>
                            <th class="col-xs-1" data-field="map_accept" data-formatter="adminMapAcceptFormatter" data-sortable="false"></th>
                            <th class="col-xs-1" data-field="map_reject" data-formatter="adminMapRejectFormatter" data-sortable="false"></th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>
