<div class="row">
    <div class="col-sm-9 col-sm-offset-2 col-md-10 col-md-offset-1 main">
        <div class="panel panel-default">
            <div class="panel-heading">
                <span class="panel-title">Flag Queue</span>
            </div>
            <div class="panel-body">
                <table id="flagQueueTable" class="table table-striped table-bordered table-hover" data-toggle="table" data-search="true" data-sort-name="flag_pk"
                        data-sort-order="asc" data-show-toggle="true" data-show-columns="true" data-minimum-count-columns="2" data-url="/api/v1/flags/queue"
                        data-show-refresh="true" data-show-pagination-switch="true" data-pagination="true" data-page-list="[25, 50, 100, ALL]"
                        data-page-size="25" data-show-footer="false" data-side-pagination="client">
                    <thead>
                        <tr>
                            <th class="col-xs-2" data-field="rev_fk" data-sortable="true">Map Revision</th>
                            <th class="col-xs-7" data-field="rev_map_file_name" data-formatter="adminFlagFileNameFormatter" data-sortable="true">Map File Name</th>
                            <th class="col-xs-2" data-field="rev_map_version" data-sortable="true">Map Version</th>
                            <th class="col-xs-1" data-field="flag_assign" data-formatter="adminFlagPickupFormatter" data-sortable="false"></th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>
<div class="row spacer">
    <div class="col-sm-9 col-sm-offset-2 col-md-10 col-md-offset-1 main">
        <div class="panel panel-default">
            <div class="panel-heading">
                <span class="panel-title">Assigned Flags</span>
            </div>
            <div class="panel-body">
                <table id="flagTable" class="table table-striped table-bordered table-hover" data-toggle="table" data-search="true" data-sort-name="flag_pk"
                        data-sort-order="asc" data-show-toggle="true" data-show-columns="true" data-minimum-count-columns="2" data-url="/api/v1/flags/mine"
                        data-show-refresh="true" data-show-pagination-switch="true" data-pagination="true" data-page-list="[25, 50, 100, ALL]"
                        data-page-size="25" data-show-footer="false" data-side-pagination="client">
                    <thead>
                        <tr>
                            <th class="col-xs-2" data-field="rev_fk" data-sortable="true">Map Revision</th>
                            <th class="col-xs-6" data-field="rev_map_file_name" data-formatter="adminFlagFileNameFormatter" data-sortable="true">Map File Name</th>
                            <th class="col-xs-2" data-field="rev_map_version" data-sortable="true">Map Version</th>
                            <th class="col-xs-1" data-field="flag_resolve" data-formatter="adminFlagResolveFormatter" data-sortable="false"></th>
                            <th class="col-xs-1" data-field="flag_close" data-formatter="adminFlagCloseFormatter" data-sortable="false"></th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>
