        <footer class="navbar-default navbar-fixed-bottom footer">
            <div class="row vertical-center">
                <div class="col-xs-3">
                    <a href="http://validator.w3.org/check?uri=referer;ss=1" style="margin-left: 15px;">
                        <img src="https://www.w3.org/html/logo/badge/html5-badge-h-css3-semantics.png" width="98px" height="38px" alt="HTML5 Powered with CSS3 / Styling, and Semantics" title="HTML5 Powered with CSS3 / Styling, and Semantics">
                    </a>
                </div>
                <div class="col-xs-6">
                    <center>
                        <span class="text-muted">Proudly created and maintained by KP-Wiki.org</span>
                    </center>
                </div>
                <div class="col-xs-3" style="text-align: right; margin-right: 15px;">
                    <a href="https://maps-docs.kp-wiki.org/" target="_blank">API docs</a>
                </div>
            </div>
        </footer>
