<!DOCTYPE html>
<html lang="en">
    <head>
        <title><?=$PageTitle;?></title>
        <meta charset="utf-8">
        <meta name="HandheldFriendly" content="true">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="description" content="Maps for Knights Province, a 3D RTS game">
        <meta name="author" content="Thimo Braker - KP-Wiki">
        <!-- Stylesheets -->
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" crossorigin="anonymous">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" crossorigin="anonymous">
        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.css" crossorigin="anonymous">
        <link rel="stylesheet" href="/css/formValidation.min.css">
        <link rel="stylesheet" href="/css/blueimp-gallery.min.css">
        <link rel="stylesheet" href="/css/main.min.css">
        <!-- Scripts -->
        <script src="/js/json2.min.js"></script>
        <script src="/js/modernizr.min.js"></script>
        <script src="//code.jquery.com/jquery-3.2.1.min.js"></script>
        <script src="//code.jquery.com/jquery-migrate-3.0.0.min.js"></script>
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" crossorigin="anonymous"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.js" crossorigin="anonymous"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js" crossorigin="anonymous"></script>
        <script src="/js/jquery.fileDownload.min.js"></script>
        <script src="/js/jquery.blueimp-gallery.min.js"></script>
        <script src="/js/tableExport.min.js"></script>
        <script src="/js/bootstrap-table-export.min.js"></script>
        <script src="/js/bootstrap-filestyle.min.js"></script>
        <script src="/js/formValidation.min.js"></script>
        <script src="/js/fv_reCaptcha2.min.js"></script>
        <script src="/js/fv_bootstrap.min.js"></script>
        <script src="/js/starrr.min.js"></script>
        <script src="/js/main.min.js"></script>
    </head>
    <body>
<?=$PageNav;?>
<?=$PageCrumbs;?>
        <div class="container-fluid">
<?=$PageContent;?>
        </div>
<?=$PageFooter;?>
    </body>
</html>
