        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-9 col-sm-offset-2 col-md-10 col-md-offset-1 main">
                    <div class="jumbotron">
                        <h1>Welcome!</h1>
                        <p>
                            This tool is meant to collect information and provide it in an easy-to-use interface.<br />
                            If there are any bugs/feature requests, please notify the SIS team.
                        </p>
                    </div>
                </div>
            </div>
        </div>
