            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-8 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-2 col-lg-offset-3 main">
                    <div class="panel panel-default">
                        <div class="panel-heading"><?=$mapName;?></div>
                        <div class="col-sm-6">
                            <div class="rating-block">
                                <h4>Average user rating</h4>
                                <h2 id="ratingAvg" class="bold padding-bottom-7">
                                    <?=$avgRating;?><small> / 5</small>
                                </h2>
                                <div class="starrr" id="ratingStarrr" kp-map-id="<?=$mapId;?>" kp-map-rating="<?=$avgRating;?>"></div><br />
                                <div id="ratingResultSuccess" class="alert alert-success alert-dismissible spacersmall" role="alert"style="display: none;">
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                    <span class="message"></span>
                                </div>
                                <div id="ratingResultError" class="alert alert-danger alert-dismissible spacersmall" role="alert" style="display: none;">
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                    <span class="message"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <h4>Breakdown</h4>
                            <div class="row" style="margin-left:2px;">
                                5 <span class="glyphicon glyphicon-star"></span>
                                <span style="margin-left:10px;"><?=$ratingFive;?> Votes</span>
                            </div>
                            <div class="row" style="margin-left:2px;">
                                4 <span class="glyphicon glyphicon-star"></span>
                                <span style="margin-left:10px;"><?=$ratingFour;?> Votes</span>
                            </div>
                            <div class="row" style="margin-left:2px;">
                                3 <span class="glyphicon glyphicon-star"></span>
                                <span style="margin-left:10px;"><?=$ratingThree;?> Votes</span>
                            </div>
                            <div class="row" style="margin-left:2px;">
                                2 <span class="glyphicon glyphicon-star"></span>
                                <span style="margin-left:10px;"><?=$ratingTwo;?> Votes</span>
                            </div>
                            <div class="row" style="margin-left:2px;">
                                1 <span class="glyphicon glyphicon-star"></span>
                                <span style="margin-left:10px;"><?=$ratingOne;?> Votes</span>
                            </div>
                        </div>
                        <table class="table table-user-information">
                            <tbody>
                                <tr>
                                    <td class="col-sm-3"><b>Author</b></td>
                                    <td class="col-sm-9">
                                        <a href="/profile/<?=$userId;?>"><?=$userName;?></a>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="col-sm-3"><b>Downloads</b></td>
                                    <td class="col-sm-9"><?=$mapDownloads;?></td>
                                </tr>
                                <tr>
                                    <td class="col-sm-3"><b>Version</b></td>
                                    <td class="col-sm-9"><?=$revMapVersion;?></td>
                                </tr>
                                <tr>
                                    <td class="col-sm-3"><b>Last change date</b></td>
                                    <td class="col-sm-9"><?=$revUploadDate;?></td>
                                </tr>
                                <tr>
                                    <td class="col-sm-3"><b>Description</b></td>
                                    <td class="col-sm-9"><?=$revMapDescription;?></td>
                                </tr>
                                <tr>
                                    <td class="col-lg-12" colspan="2">
                                        <button class="btn btn-success" id="btnDownloadMap" type="submit" title="Download this map"
                                                kp-map-id="<?=$revId;?>">
                                            <span class="glyphicon glyphicon-download-alt"></span>&nbsp;&nbsp;Download
                                        </button>
                                        <?php
                                            if ($userId == $_SESSION['user']->id) {
                                        ?>
                                        &nbsp;&nbsp;
                                        <a class="btn btn-primary" id="btnUpdateMapInfo" title="Edit Map Information"
                                           href="/map/<?=$mapId;?>/edit" role="button">
                                            <span class="glyphicon glyphicon-pencil"></span>&nbsp;&nbsp;Edit Info
                                        </a>
                                        <?php
                                            };
                                        ?>
                                        <button class="btn btn-danger pull-right" id="btnFlagMap" type="submit" title="Flag this map"
                                                kp-map-id="<?=$revId;?>">
                                            <span class="glyphicon glyphicon-flag"></span>
                                        </button>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="row spacer">
                <div class="col-xs-12 col-sm-12 col-md-8 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-2 col-lg-offset-3" style="margin-bottom: 25px;">
                    <center>
                        <div id="screenshot_carousel" class="carousel slide" data-ride="carousel">
                            <!-- Indicators -->
                            <ol class="carousel-indicators">
                                <?=$carouselIndicators;?>
                            </ol>
                            <!-- Wrapper for slides -->
                            <center>
                                <div class="carousel-inner" role="listbox">
                                    <?=$carouselItems;?>
                                </div>
                            </center>
                            <!-- Controls -->
                            <a class="left carousel-control" href="#screenshot_carousel" role="button" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                            <a class="right carousel-control" href="#screenshot_carousel" role="button" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
                        </div>
                    </center>
                </div>
            </div>