<div class="row">
    <div class="col-sm-9 col-sm-offset-2 col-md-10 col-md-offset-1 main">
        <div class="stepwizard col-md-offset-3">
            <div class="stepwizard-row setup-panel">
                <div class="stepwizard-step">
                    <a href="#step-1" type="button" class="btn btn-primary btn-circle">
                        <span class="glyphicon glyphicon-folder-open"></span>
                    </a>
                    <p>Step 1</p>
                </div>
                <div class="stepwizard-step">
                    <a href="#step-2" type="button" class="btn btn-default btn-circle disabled" disabled="disabled">
                        <span class="glyphicon glyphicon-edit"></span>
                    </a>
                    <p>Step 2</p>
                </div>
                <div class="stepwizard-step">
                    <a href="#step-3" type="button" class="btn btn-default btn-circle disabled" disabled="disabled">
                        <span class="glyphicon glyphicon-picture"></span>
                    </a>
                    <p>Step 3</p>
                </div>
            </div>
        </div>
        <form enctype="multipart/form-data" id="uploadMapFrm" name="uploadMapFrm" role="form">
            <div class="row setup-content" id="step-1">
                <div class="col-xs-6 col-md-offset-3">
                    <div class="col-md-12">
                        <h3>Select the map files</h3>
                        <div class="form-group required">
                            <label for="mapFile" class="control-label">.MAP File</label>
                            <input type="file" id="mapFile" name="mapFile" class="filestyle" data-buttonName="btn-primary"
                                    data-buttonBefore="true" data-iconName="glyphicon glyphicon-open-file" accept=".map" required>
                        </div>
                        <div class="form-group required">
                            <label for="datFile" class="control-label">.DAT File</label>
                            <input type="file" id="datFile" name="datFile" class="filestyle" data-buttonName="btn-primary"
                                    data-buttonBefore="true" data-iconName="glyphicon glyphicon-open-file" accept=".dat" required>
                        </div>
                        <div class="form-group">
                            <label for="scriptFile">.SCRIPT File</label>
                            <input type="file" id="scriptFile" name="scriptFile" class="filestyle" data-buttonName="btn-primary"
                                    data-buttonBefore="true" data-iconName="glyphicon glyphicon-open-file" accept=".script">
                        </div>
                        <div class="form-group">
                            <label for="libxFiles">.LIBX File(s)</label>
                            <span class="help-block helpermarginfix">
                                These are files that hold the translations for your dynamic script texts<br />
                                More information <a href="https://github.com/Kromster80/knights_province/wiki" target="_blank">Github wiki</a>
                            </span>
                            <input type="file" id="libxFiles" name="libxFiles[]" class="filestyle" data-buttonName="btn-primary"
                                    data-buttonBefore="true" data-iconName="glyphicon glyphicon-open-file" accept=".libx" multiple>
                        </div>
                        <button class="btn btn-primary nextBtn btn-lg pull-right" type="button" >Next</button>
                    </div>
                </div>
            </div>
            <div class="row setup-content" id="step-2">
                <div class="col-xs-6 col-md-offset-3">
                    <div class="col-md-12">
                        <h3>Provide information about the map</h3>
                        <div class="form-group required">
                            <label for="mapName" class="control-label">Map Name</label>
                            <input type="text" id="mapName" name="mapName" class="form-control" required>
                        </div>
                        <div class="form-group required">
                            <label for="mapType" class="control-label">Map Type</label>
                            <select id="mapType" name="mapType" class="form-control" required>
                                <?=$mapTypes?>
                            </select>
                        </div>
                        <div class="form-group required">
                            <label for="mapVersion" class="control-label">Map Version</label>
                            <input type="text" id="mapVersion" name="mapVersion" class="form-control" required>
                        </div>
                        <div class="form-group required">
                            <label for="mapDescShort" class="control-label">Short Description</label>
                            <input type="text" id="mapDescShort" name="mapDescShort" class="form-control" required>
                        </div>
                        <div class="form-group required">
                            <label for="mapDescFull" class="control-label">Full Description</label>
                            <textarea id="mapDescFull" name="mapDescFull" class="form-control" rows="3" required></textarea>
                        </div>
                        <button class="btn btn-primary nextBtn btn-lg pull-right" type="button" >Next</button>
                    </div>
                </div>
            </div>
            <div class="row setup-content" id="step-3">
                <div class="col-xs-6 col-md-offset-3">
                    <div class="col-md-12">
                        <h3>Add some screenshots for the map</h3>
                        <div class="panel panel-default">
                            <div class="panel-heading">Screenshot 1</div>
                            <div class="panel-body">
                                <div class="form-group">
                                    <label for="screenshotTitleOne">Title</label>
                                    <input type="text" id="screenshotTitleOne" name="screenshotTitleOne" class="form-control">
                                </div>
                                <div class="form-group">
                                    <label for="screenshotFileOne">File</label>
                                    <input type="file" id="screenshotFileOne" name="screenshotFileOne" class="filestyle" data-buttonName="btn-primary"
                                            data-buttonBefore="true" data-iconName="glyphicon glyphicon-open-file" accept="image/*">
                                </div>
                            </div>
                        </div>
                        <div class="panel panel-default">
                            <div class="panel-heading">Screenshot 2</div>
                            <div class="panel-body">
                                <div class="form-group">
                                    <label for="screenshotTitleTwo">Title</label>
                                    <input type="text" id="screenshotTitleTwo" name="screenshotTitleTwo" class="form-control">
                                </div>
                                <div class="form-group">
                                    <label for="screenshotFileTwo">File</label>
                                    <input type="file" id="screenshotFileTwo" name="screenshotFileTwo" class="filestyle" data-buttonName="btn-primary"
                                            data-buttonBefore="true" data-iconName="glyphicon glyphicon-open-file" accept="image/*">
                                </div>
                            </div>
                        </div>
                        <div class="panel panel-default">
                            <div class="panel-heading">Screenshot 3</div>
                            <div class="panel-body">
                                <div class="form-group">
                                    <label for="screenshotTitleThree">Title</label>
                                    <input type="text" id="screenshotTitleThree" name="screenshotTitleThree" class="form-control">
                                </div>
                                <div class="form-group">
                                    <label for="screenshotFileThree">File</label>
                                    <input type="file" id="screenshotFileThree" name="screenshotFileThree" class="filestyle" data-buttonName="btn-primary"
                                            data-buttonBefore="true" data-iconName="glyphicon glyphicon-open-file" accept="image/*">
                                </div>
                            </div>
                        </div>
                        <div class="panel panel-default">
                            <div class="panel-heading">Screenshot 4</div>
                            <div class="panel-body">
                                <div class="form-group">
                                    <label for="screenshotTitleFour">Title</label>
                                    <input type="text" id="screenshotTitleFour" name="screenshotTitleFour" class="form-control">
                                </div>
                                <div class="form-group">
                                    <label for="screenshotFileFour">File</label>
                                    <input type="file" id="screenshotFileFour" name="screenshotFileFour" class="filestyle" data-buttonName="btn-primary"
                                            data-buttonBefore="true" data-iconName="glyphicon glyphicon-open-file" accept="image/*">
                                </div>
                            </div>
                        </div>
                        <div class="panel panel-default">
                            <div class="panel-heading">Screenshot 5</div>
                            <div class="panel-body">
                                <div class="form-group">
                                    <label for="screenshotTitleFive">Title</label>
                                    <input type="text" id="screenshotTitleFive" name="screenshotTitleFive" class="form-control">
                                </div>
                                <div class="form-group">
                                    <label for="screenshotFileFive">File</label>
                                    <input type="file" id="screenshotFileFive" name="screenshotFileFive" class="filestyle" data-buttonName="btn-primary"
                                            data-buttonBefore="true" data-iconName="glyphicon glyphicon-open-file" accept="image/*">
                                </div>
                            </div>
                        </div>
                        <button type="submit" id="submitNewMap" name="submitNewMap" class="btn btn-primary pull-right">Submit</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>