<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-2 col-lg-offset-3 main">
        <form enctype="multipart/form-data" method="POST" kp-map-id="<?=$mapId;?>" id="editMapFilesFrm" name="editMapFilesFrm" role="form">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <span class="panel-title"><?=$mapName;?></span>
                </div>
                <table class="table table-user-information">
                    <tbody>
                        <tr>
                            <td class="col-sm-3"><b>Map Version <span style="color: red;">*</span></b></td>
                            <td class="col-sm-9">
                                <input type="text" id="editMapRevVersion" name="editMapRevVersion" class="form-control"
                                        value="<?=$revMapVersion;?>" required>
                            </td>
                        </tr>
                        <tr>
                            <td class="col-sm-3"><b>.MAP File <span style="color: red;">*</span></b></td>
                            <td class="col-sm-9">
                                <input type="file" id="editMapMapFile" name="editMapMapFile" class="filestyle" data-buttonName="btn-primary"
                                        data-buttonBefore="true" data-iconName="glyphicon glyphicon-open-file" accept=".map" required>
                            </td>
                        </tr>
                        <tr>
                            <td class="col-sm-3"><b>.DAT File <span style="color: red;">*</span></b></td>
                            <td class="col-sm-9">
                                <input type="file" id="editMapDatFile" name="editMapDatFile" class="filestyle" data-buttonName="btn-primary"
                                        data-buttonBefore="true" data-iconName="glyphicon glyphicon-open-file" accept=".dat" required>
                            </td>
                        </tr>
                        <tr>
                            <td class="col-sm-3"><b>.SCRIPT File</b></td>
                            <td class="col-sm-9">
                                <input type="file" id="editMapScriptFile" name="editMapScriptFile" class="filestyle" data-buttonName="btn-primary"
                                        data-buttonBefore="true" data-iconName="glyphicon glyphicon-open-file" accept=".script">
                            </td>
                        </tr>
                        <tr>
                            <td class="col-sm-3"><b>.LIBX File(s)</b></td>
                            <td class="col-sm-9">
                                <input type="file" id="editMapLibxFiles" name="editMapLibxFiles[]" class="filestyle" data-buttonName="btn-primary"
                                        data-buttonBefore="true" data-iconName="glyphicon glyphicon-open-file" accept=".libx" multiple>
                            </td>
                        </tr>
                        <tr>
                            <td class="col-lg-12" colspan="2">
                                <button class="btn btn-success" type="submit" title="Submit New Map Revision">
                                    <span class="glyphicon glyphicon-floppy-save"></span>&nbsp;&nbsp;Submit
                                </button>
                                <a class="btn btn-danger pull-right" id="btnCancelUpdateMapFiles" title="Cancel" href="/map/<?=$mapId;?>" role="button">
                                    <span class="glyphicon glyphicon-remove"></span>&nbsp;&nbsp;Cancel
                                </a>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </form>
    </div>
</div>