            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-8 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-2 col-lg-offset-3 main">
                    <form method="post" enctype="multipart/form-data" action="/map/<?=$mapId;?>/updateinfo" id="editMapInfoFrm" role="form">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <span class="panel-title"><?=$mapName;?></span>
                            </div>
                            <table class="table table-user-information">
                                <tbody>
                                    <tr>
                                        <td class="col-sm-3"><b>Short Description</b></td>
                                        <td class="col-sm-9">
                                            <input type="text" id="editMapDescShort" name="editMapDescShort" class="form-control"
                                                   value="<?=nl2br($revMapDescriptionShort);?>" required>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="col-sm-3"><b>Full Description</b></td>
                                        <td class="col-sm-9">
                                            <textarea id="editMapDescFull" name="editMapDescFull" class="form-control"
                                                      rows="3" required><?=$revMapDescription;?></textarea>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="col-lg-12" colspan="2">
                                            <button class="btn btn-success" type="submit" title="Submit new Map Information">
                                                <span class="glyphicon glyphicon-floppy-save"></span>&nbsp;&nbsp;Submit
                                            </button>
                                            <a class="btn btn-danger pull-right" id="btnCancelUpdateMapInfo" title="Cancel"
                                               href="/map/<?=$mapId;?>" role="button">
                                                <span class="glyphicon glyphicon-remove"></span>&nbsp;&nbsp;Cancel
                                            </a>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </form>
                </div>
            </div>