<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/home">KP-Maps</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li role="presentation"<?=($PageID == 0 ? " class=\"active\"" : "");?>>
                    <a href="/home" title="Home">
                        <span class="glyphicon glyphicon-home"></span>
                    </a>
                </li>
                <li role="presentation"<?=($PageID == 1 ? " class=\"active\"" : "");?>>
                    <a href="/about" title="About">
                        <span class="glyphicon glyphicon-info-sign"></span>
                    </a>
                </li>
                <li role="presentation">
                    <a href="http://knightsprovince.com" target="_blank" title="Go to the Knights Province website">
                        <span class="glyphicon glyphicon-globe"></span>&nbsp;&nbsp;Knights Provice
                    </a>
                </li>
                <li role="presentation">
                    <a href="https://kp-wiki.org" target="_blank" title="Go to the KP-Wiki website">
                        <span class="glyphicon glyphicon-globe"></span>&nbsp;&nbsp;KP-Wiki
                    </a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        <span class="glyphicon glyphicon-user"></span>&nbsp;&nbsp;<span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li role="presentation">
                            <a href="#loginModal" data-toggle="modal">
                                <span class="glyphicon glyphicon-log-in"></span>&nbsp;&nbsp;Login
                            </a>
                        </li>
                        <li role="separator" class="divider"></li>
                        <li role="presentation">
                            <a href="#RegisterModal" data-toggle="modal">
                                <span class="glyphicon glyphicon-pencil"></span>&nbsp;&nbsp;Register
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>
<!-- Begin Modal HTML -->
<div id="loginModal" class="modal fade">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">Login</h4>
            </div>
            <div class="modal-body">
                <div class="col-md-12 col-sm-12 no-padng">
                    <div class="logreg-model">
                        <form method="post" action="/login" id="loginFrm" name="loginFrm" class="logreg-frm">
                            <ul>
                                <li>Username or Email</li>
                                <li>
                                    <input type="text" placeholder="Username/Email" id="username" name="username" class="form-control" required>
                                </li>
                                <li>Password</li>
                                <li>
                                    <input type="password" placeholder="Password" id="password" name="password" class="form-control" required>
                                </li><br />
                                <li>
                                    <button type="submit" id="logBtn" class="btn btn-default">Submit</button>
                                </li>
                            </ul>
                        </form>
                        <div class="clearfix"></div>
                        <form method="post" action="/forgot" id="forgotFrm" name="forgotFrm" class="logreg-frm">
                            <ul>
                                <li>
                                    <a class="forgot-link" onclick="toggleForgot();" href="javascript:;">Forgot your password?</a>
                                    <div class="logreg-forgot">
                                        <ul>
                                            <li><p>Enter your Email Address here to receive a link to change password.</p></li>
                                            <li>Email</li>
                                            <li>
                                                <input type="email" placeholder="Your email" id="forgetemail" class="form-control" name="forgetemail" required>
                                            </li>
                                            <li>
                                                <button type="submit" class="btn btn-default">Send Mail</button>
                                            </li>
                                        </ul>
                                    </div>
                                </li>
                            </ul>
                        </form>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</div>
<div id="RegisterModal" class="modal fade">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">Register</h4>
            </div>
            <div class="modal-body">
                <div class="col-md-12 col-sm-12 no-padng">
                    <div class="logreg-model">
                        <form method="post" action="/register" id="userRegisterFrm" name="userRegisterFrm" class="logreg-frm">
                            <ul>
                                <li>Username</li>
                                <li>
                                    <input type="text" id="username" name="username" placeholder="Username" class="form-control" required>
                                </li>
                                <li>Email</li>
                                <li>
                                    <input type="email" id="emailAddress" name="emailAddress" placeholder="Email" class="form-control" required>
                                    <input type="email" id="confirmEmailAddress" name="confirmEmailAddress" placeholder="Confirm Email" class="form-control" style="display: none;">
                                </li>
                                <li>Password</li>
                                <li>
                                    <input type="password" id="password" name="password" placeholder="Password" class="form-control" required>
                                </li>
                                <li>Confirm Password</li>
                                <li>
                                    <input type="password" id="confirmPassword" name="confirmPassword" placeholder="Confirm Password" class="form-control" required>
                                </li>
                                <br />
                                <li>
                                    <div id="captchaContainer"></div>
                                </li>
                                <br />
                                <li>
                                    <button type="submit" id="userRegBtn" name="userRegBtn" class="btn btn-default" disabled>Signup Now</button>
                                    <button type="button" id="userRegResetBtn" name="userRegResetBtn" class="btn btn-default">Reset</button>
                                </li>
                            </ul>
                        </form>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</div>
<!-- End Modal HTML -->
