            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-8 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-2 col-lg-offset-3 main">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <span class="panel-title">Info Card</span>
                        </div>
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-md-3 col-lg-3" align="center">
                                    <img class="img-rounded img-responsive" alt="" src="<?=$user['gravatar'];?>">
                                </div>
                                <div class="col-md-9 col-lg-9">
                                    <table class="table table-user-information">
                                        <tbody>
                                            <tr>
                                                <td><span class="glyphicon glyphicon-user"></span>&nbsp;&nbsp;Username</td>
                                                <td>
                                                    <?=$user['user_name'];?>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td><span class="glyphicon glyphicon-tag"></span>&nbsp;&nbsp;Group</td>
                                                <td>
                                                    <?=$user['group_name'];?>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>